version: '3'

tasks:
  build:
    desc: 执行生产环境构建
    cmds:
      - echo ">>> 构建中..."
      - pnpm run build

  publish:
    desc: 构建并发布到 npm
    cmds:
      - task: build
      - echo ">>> 发布中..."
      - pnpm login --registry=https://registry.npmjs.org
      - pnpm publish --no-git-checks
      - echo ">>> 发布完成！"
